title: Dream Home
email: cvetelina.min.georgieva@gmail.com
description: Find your dream house
destination: docs
baseurl: "/css-advanced-project"
# baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

collections:
  agents:
  categories:

exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - gulpfile.js
  - theme-personal 

